import { useState } from "react";

const principles = [["◇", "Simplicidade"], ["⚡", "Performance"], ["Aa", "Legibilidade"], ["◎", "Comunidade"], ["↗", "Open Source"], ["✦", "Produtividade"], ["◌", "Segurança"], ["⌘", "Aprendizado"]];
const uses = ["Aplicações Desktop", "Sites", "APIs", "Automação", "Jogos", "Ferramentas", "Bots", "Ensino", "Scripts"];
const faq = [["O que é a JLScript?", "Uma linguagem de programação em português, criada para tornar o desenvolvimento mais acessível."], ["Quem pode utilizar?", "Estudantes, iniciantes e desenvolvedores que querem uma sintaxe clara e moderna."], ["É gratuita e Open Source?", "Sim. A JLScript é um projeto aberto, distribuído sob licença MIT."], ["Quais sistemas operacionais são suportados?", "O projeto possui foco inicial em Windows, com evolução para Linux e macOS."], ["Como instalar?", "Acesse a página Download e siga o comando recomendado para seu sistema."], ["Preciso saber outra linguagem antes?", "Não. A linguagem foi pensada para ser um ponto de entrada amigável na programação."], ["Qual a diferença entre JLScript e JavaScript?", "JLScript tem sintaxe e runtime próprios, com palavras em português e foco didático."], ["A JLScript possui compilador e interpretador?", "O interpretador já existe. O compilador está em desenvolvimento."], ["Existe uma IDE oficial?", "Ainda não. A extensão oficial do VS Code está disponível e uma IDE faz parte do roadmap."], ["Como criar meu primeiro projeto?", "Instale a linguagem, crie um arquivo app.jls e execute com o comando jls."], ["Como contribuir ou reportar bugs?", "Use o GitHub para abrir issues, discutir ideias e enviar melhorias."], ["Como instalar bibliotecas?", "O sistema de pacotes está em desenvolvimento; os módulos oficiais usam importações nativas."], ["O Playground executa código real?", "Ele executa um subconjunto seguro de recursos básicos diretamente no navegador."], ["Existe documentação oficial?", "Sim. A documentação fica disponível no menu do site e cresce junto com a linguagem."], ["A linguagem continuará sendo desenvolvida?", "Sim. A evolução aberta do ecossistema é um dos pilares do projeto."]];

function Heading({ eyebrow, title, text }) { return <header className="about-heading"><p>{eyebrow}</p><h2>{title}</h2>{text && <span>{text}</span>}</header>; }
export default function About() { const [open, setOpen] = useState(0); return <>
  <section className="about-hero"><div><p>ACERCA DA LINGUAGEM</p><h1>Sobre a <span>JLScript</span></h1><h2>Uma linguagem criada para simplificar o desenvolvimento e tornar a programação mais acessível para todos.</h2><a className="btn" href="#/docs">Conhecer a documentação →</a></div><div className="about-art"><i>▣</i><b>func criar(futuro) {'{'}</b><small>programação em português</small><em>{'}'}</em></div></section>
  <section className="about-section history"><Heading eyebrow="NOSSA HISTÓRIA" title="Uma ideia nascida para diminuir barreiras." text="A JLScript surgiu da vontade de aproximar mais brasileiros da programação. Ela busca reduzir a complexidade inicial sem perder uma base técnica séria, inspirada por linguagens modernas como Python, Go, Rust e JavaScript." /><div className="timeline"><div><b>Ideia</b><span>Uma sintaxe em português para aprender com mais clareza.</span></div><div><b>Fundação</b><span>Primeiros comandos, lexer, parser e interpretador.</span></div><div><b>Ecossistema</b><span>CLI, extensão VS Code e documentação oficial.</span></div><div><b>Futuro</b><span>Compilador, packages, playground e IDE oficial.</span></div></div></section>
  <section className="about-section mission"><Heading eyebrow="NOSSA MISSÃO" title="Tecnologia mais próxima das pessoas." /><div>{["Tornar a programação mais simples", "Facilitar o aprendizado", "Aproximar iniciantes da tecnologia", "Manter uma sintaxe limpa", "Ser Open Source", "Incentivar a comunidade brasileira"].map(item => <p key={item}>✓ {item}</p>)}</div></section>
  <section className="about-section"><Heading eyebrow="NOSSA FILOSOFIA" title="Princípios que guiam cada decisão." /><div className="principles">{principles.map(([icon, name]) => <article key={name}><span>{icon}</span><h3>{name}</h3></article>)}</div></section>
  <section className="about-section reasons"><Heading eyebrow="POR QUE JLSCRIPT?" title="Uma base clara para criar mais." /><div>{["Sintaxe intuitiva", "Palavras em português", "Fácil para iniciantes", "Organização de código", "Alto desempenho", "Extensível", "CLI própria", "Documentação completa", "IDE futuramente", "Playground online"].map(x => <p key={x}>✓ {x}</p>)}</div></section>
  <section className="about-section objectives"><Heading eyebrow="OBJETIVOS" title="Construir um ecossistema que evolui." /><div>{["Linguagem moderna", "Compilador oficial", "Gerenciador de pacotes", "IDE oficial", "Múltiplas plataformas", "Comunidade ativa", "Documentação completa", "Playground online"].map((x, i) => <article key={x}><b>0{i + 1}</b><span>{x}</span></article>)}</div></section>
  <section className="about-section"><Heading eyebrow="ROADMAP" title="A direção do projeto." /><div className="about-roadmap"><article><h3>Concluído</h3><p>✅ Interpretador</p><p>✅ CLI</p><p>✅ Extensão VS Code</p></article><article><h3>Em desenvolvimento</h3><p>🚧 Compilador</p><p>🚧 Playground</p><p>🚧 Package Manager</p><p>🚧 Biblioteca Oficial</p></article><article><h3>Planejado</h3><p>🔵 IDE Oficial</p><p>🔵 Depurador</p><p>🔵 LSP</p><p>🔵 IA integrada</p></article></div></section>
  <section className="about-section"><Heading eyebrow="CASOS DE USO" title="Uma linguagem, muitas possibilidades." /><div className="uses">{uses.map(use => <article key={use}>◈ <span>{use}</span></article>)}</div></section>
  <section className="about-section faq"><Heading eyebrow="PERGUNTAS FREQUENTES" title="Dúvidas comuns." />{faq.map(([question, answer], index) => <article className={open === index ? "open" : ""} key={question}><button onClick={() => setOpen(open === index ? -1 : index)}>{question}<b>{open === index ? "−" : "+"}</b></button>{open === index && <p>{answer}</p>}</article>)}</section>
  <section className="about-section tech"><Heading eyebrow="TECNOLOGIAS" title="Feita com ferramentas abertas." /><div>{["C++", "Visual Studio Code", "GitHub", "Markdown", "JSON", "Node.js", "React"].map(tech => <span key={tech}>{tech}</span>)}</div></section>
  <section className="about-community"><p>FAÇA PARTE DA COMUNIDADE JLSCRIPT</p><h2>Ajude a construir uma linguagem feita para a comunidade.</h2><span>Contribua com ideias, relate problemas, envie melhorias e acompanhe a evolução do projeto.</span><div><a className="btn" href="#/docs">Começar agora</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">GitHub ↗</a><a className="btn-outline" href="#/download">Download</a></div></section>
</>; }
