import { useState } from "react";
import { DownloadSection, PageHeading } from "../components/Ecosystem";
import { RELEASE_BASE, VERSION } from "../data/downloads";

const Code = ({ children }) => <pre className="doc-code"><code>{children}</code></pre>;
const termuxCommand = "pkg install curl\ncurl -fsSL https://jlscript.dev/install-termux.sh | bash";
const guides = [["Windows", "Baixe o instalador .exe recomendado. Ele instala a CLI, adiciona a pasta ao PATH e oferece atalho opcional.", "Baixar o .exe acima e executar"], ["Linux", "Detecta x64 ou ARM64, instala em ~/.local e configura ~/.local/bin no PATH.", "curl -fsSL https://jlscript.dev/install.sh | bash"], ["macOS", "O instalador detecta Intel ou Apple Silicon e prepara a CLI no PATH.", "curl -fsSL https://jlscript.dev/install.sh | bash"]];

function TermuxGuide() {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard?.writeText(termuxCommand); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  return <section className="termux-guide"><div><p>ANDROID · TERMUX</p><h2>JLScript no seu celular.</h2><span>Instalação oficial automática. Em ARM64, o instalador baixa um binário publicado; se ainda não existir, compila a versão atual diretamente no Termux.</span><Code>{termuxCommand}</Code></div><aside><b>Depois de instalar</b><code>jls --version</code><code>jls new MeuProjeto</code><code>jls ai</code><div><button className="btn" onClick={copy}>{copied ? "✓ Copiado" : "Copiar comando"}</button><a className="btn-outline" href="#/terminal">Abrir documentação</a></div></aside></section>;
}

export default function DownloadPage() { return <><PageHeading eyebrow="DOWNLOADS" title="Baixe a JLScript." text="Instalação simples para Windows, Linux, macOS e Android com Termux." /><section className="download-version"><span>VERSAO ATUAL</span><h2>JLScript <b>v{VERSION}</b></h2><div><p>✓ Interpretador e CLI</p><p>✓ Extensao VS Code</p><p>✓ Atualizacoes gratuitas</p><p>✓ Codigo aberto</p></div></section><DownloadSection /><TermuxGuide /><section className="download-details">{guides.map(([name, description, command]) => <article key={name}><h2>{name}</h2><p>{description}</p><h3>Instalação</h3><Code>{command}</Code><p className="download-note">Depois confirme com: jls version</p></article>)}</section><section className="download-docs"><article><h2>Atualizar</h2><p>Quando uma nova Release estiver disponível:</p><Code>jls update</Code></article><article><h2>Desinstalar</h2><p>Windows: use Aplicativos instalados ou o atalho Desinstalar JLScript. No Termux:</p><Code>jls uninstall</Code></article><article><h2>Verificar</h2><p>Diagnostique PATH, executável e ambiente:</p><Code>jls doctor</Code></article><article><h2>Releases e integridade</h2><p>Os hashes SHA-256 acompanham os assets das Releases.</p><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/releases" target="_blank" rel="noreferrer">Abrir Releases →</a></article><article><h2>Changelog</h2><p>A versão {VERSION} inclui CLI, interpretador, compilação inicial, JLAI e extensão VS Code.</p><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/releases" target="_blank" rel="noreferrer">Ver mudanças →</a></article><article><h2>Origem dos pacotes</h2><Code>{RELEASE_BASE}</Code></article></section></>; }
