import { PageHeading } from "../components/Ecosystem";

const Code = ({ children }) => <pre className="doc-code"><code>{children}</code></pre>;
export default function Library() { return <><PageHeading eyebrow="BIBLIOTECAS E APIS" title="Código organizado. Integrações simples." text="Na JLScript, bibliotecas e APIs reutilizam código, mas cada uma tem um propósito específico." />
  <section className="library-page">
    <article className="library-intro"><h2>Biblioteca</h2><p>Uma biblioteca agrupa funções reutilizáveis que executam tarefas locais, sem depender de serviços externos. É indicada para matemática, texto, datas, arquivos, criptografia, utilitários, conversões e estruturas de dados.</p><Code>{`info{\n    nome: "Math"\n    versao: "1.0.0"\n}\n\nbiblioteca Math{\n    somar(a, b){\n        retorne a + b\n    }\n\n    multiplicar(a, b){\n        retorne a * b\n    }\n}`}</Code><h3>Uso</h3><Code>{`usar(#math)\n\nva resultado = math.somar(10, 20)\n\nmostrar(resultado)`}</Code></article>
    <article className="library-intro api-intro"><h2>API</h2><p>O bloco <code>api</code> é uma biblioteca especializada para consumir APIs HTTP e HTTPS. O runtime gerencia a comunicação para manter o código simples e legível.</p><p>Dentro dela é possível definir URL base, endpoints, headers, timeout, cache e métodos GET, POST, PUT e DELETE.</p><Code>{`info{\n    nome: "Github"\n    versao: "1.0.0"\n}\n\napi Github{\n    base "https://api.github.com"\n\n    usuario(nome){\n        retorne get("/users/" + nome)\n    }\n\n    repositorios(nome){\n        retorne get("/users/" + nome + "/repos")\n    }\n}`}</Code><h3>Uso</h3><Code>{`usar(#github)\n\nva usuario = github.usuario("eohlczinn")\n\nmostrar(usuario.name)\nmostrar(usuario.followers)`}</Code></article>
    <section className="library-compare"><h2>Qual a diferença?</h2><div className="compare-table"><div><b>Biblioteca</b><p>Executa funções locais.</p><p>Não possui recursos de rede nativos.</p><p>Ideal para cálculos, arquivos, texto e utilidades.</p><p>Não depende de internet.</p></div><div><b>API</b><p>Consome serviços HTTP/HTTPS.</p><p>Possui recursos nativos para requisições web.</p><p>Ideal para integrar sistemas e serviços externos.</p><p>Pode depender de conexão com a internet.</p></div></div></section>
    <section className="library-philosophy"><p>FILOSOFIA DA JLSCRIPT</p><h2>Uma API é uma biblioteca especializada.</h2><span>Ambas compartilham a filosofia de simplicidade; o bloco <code>api</code> adiciona recursos próprios para comunicação com serviços web. O objetivo é escrever menos código sem abrir mão de organização e legibilidade.</span><small>Observação: a JLScript ainda está em desenvolvimento. A sintaxe e os recursos desta página podem mudar até a versão estável.</small></section>
  </section>
</>; }
