import { useState } from "react";

const shortcuts = [["📚", "Documentação", "#/docs"], ["🐞", "Reportar Bug", "https://github.com/eohlczinn/JLScript/issues"], ["💡", "Solicitar Funcionalidade", "https://github.com/eohlczinn/JLScript/issues"], ["❓", "Perguntas Frequentes", "#faq"], ["📦", "Bibliotecas", "#/biblioteca"], ["⚙", "Instalação", "#/download"], ["💻", "Playground", "#/playground"], ["🚀", "Downloads", "#/download"]];
const faqs = [["O que é a JLScript?", "Uma linguagem em português, pensada para tornar o desenvolvimento mais simples e acessível."], ["Como instalar ou atualizar a linguagem?", "Acesse Downloads e use o comando recomendado. Para atualizar, use jls update."], ["Como criar e executar meu primeiro projeto?", "Crie um arquivo app.jls, escreva seu código e execute com jls run app.jls."], ["Como instalar e importar bibliotecas?", "Os módulos oficiais usam importações nativas. O gerenciador de pacotes está em desenvolvimento."], ["Como criar funções, variáveis, loops e condições?", "A documentação contém exemplos de va, ins, func, repita, enquanto, se e senao."], ["Como utilizar o Playground?", "Abra a página Playground, escreva ou escolha um exemplo e clique em Executar."], ["O Playground possui limitações?", "Sim. Por segurança, ele bloqueia internet, sistema operacional, arquivos e bibliotecas externas."], ["Como reportar um bug ou contribuir?", "Abra uma issue no GitHub oficial com uma descrição e exemplo para reproduzir o problema."], ["Como baixar versões antigas?", "Consulte as Releases do repositório oficial no GitHub."], ["A JLScript é gratuita e Open Source?", "Sim. O projeto é aberto e distribuído sob licença MIT."], ["Há suporte para Windows, Linux e macOS?", "Windows é o foco atual; Linux e macOS fazem parte da expansão do projeto."], ["Existe IDE oficial?", "Ainda não. A extensão do VS Code está disponível e a IDE consta no roadmap."], ["Como entrar na comunidade?", "Participe pelo GitHub: issues, discussões, sugestões e contribuições são bem-vindas."]];
function SupportHeading({ title, children }) { return <header className="support-heading"><p>CENTRAL DE SUPORTE</p><h2>{title}</h2>{children && <span>{children}</span>}</header>; }

export default function Support() { const [open, setOpen] = useState(-1); return <section className="support-page-new">
  <header className="support-hero"><div><p>CENTRAL DE SUPORTE</p><h1>Como podemos <span>ajudar?</span></h1><h2>Encontre ajuda, tire dúvidas, reporte problemas e contribua com o desenvolvimento da JLScript.</h2><a className="btn" href="#/docs">Abrir documentação →</a></div><div className="support-art"><b>?</b><span>suporte técnico<br />para criar sem travas</span></div></header>
  <section className="support-block"><SupportHeading title="Encontre o que precisa." /><div className="support-shortcuts">{shortcuts.map(([icon, label, href]) => <article key={label}><span>{icon}</span><h3>{label}</h3><a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel="noreferrer">Abrir →</a></article>)}</div></section>
  <section id="faq" className="support-block support-faq"><SupportHeading title="Perguntas frequentes." />{faqs.map(([question, answer], i) => <article key={question}><button onClick={() => setOpen(open === i ? -1 : i)}>{question}<b>{open === i ? "−" : "+"}</b></button>{open === i && <p>{answer}</p>}</article>)}</section>
  <section className="support-actions"><article><span>🐞</span><h2>Reportar problemas</h2><p>Encontrou um bug? Relatar problemas ajuda a tornar a JLScript melhor para todos.</p><div><a className="btn" href="https://github.com/eohlczinn/JLScript/issues/new" target="_blank" rel="noreferrer">Reportar Bug</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues" target="_blank" rel="noreferrer">Ver Issues</a></div></article><article><span>💡</span><h2>Solicitar recursos</h2><p>Tem uma ideia para melhorar a JLScript? Compartilhe sugestões de novos recursos, melhorias ou otimizações.</p><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues/new" target="_blank" rel="noreferrer">Solicitar funcionalidade →</a></article></section>
  <section className="github-official"><p>GITHUB OFICIAL</p><h2>Todo o desenvolvimento acontece de forma aberta.</h2><span>Acompanhe atualizações, envie sugestões, relate problemas e contribua diretamente com o projeto.</span><code>github.com/eohlczinn/JLScript</code><div><a className="btn" href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">Abrir GitHub ↗</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/releases" target="_blank" rel="noreferrer">Ver Releases</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues" target="_blank" rel="noreferrer">Abrir Issues</a></div></section>
  <section className="support-block"><SupportHeading title="Status do projeto." /><div className="project-status">{["Desenvolvimento ativo", "Open Source", "Atualizações frequentes", "Comunidade aberta"].map(status => <p key={status}>● {status}</p>)}</div></section>
  <section className="support-help"><h2>Precisa de mais ajuda?</h2><p>Caso não encontre a resposta na documentação, visite o repositório oficial para abrir uma issue, acompanhar a linguagem ou contribuir diretamente.</p><div><a className="btn" href="#/docs">Documentação</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">GitHub</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues/new" target="_blank" rel="noreferrer">Reportar Bug</a></div></section>
</section>; }
