const downloads = [["▣", "Windows", ".exe", "Baixar para Windows"], ["⌘", "macOS", "Apple Silicon e Intel", "Em breve"], ["◒", "Linux", "x64 e ARM", "Em breve"], ["▤", "Termux", "Android", "Em breve"], ["◈", "VS Code Extension", "Autocomplete oficial", "Instalar extensão"]];
const updates = [["Lançamento da versão 1.0", "Uma base mais forte para a próxima etapa da JLScript.", "Produto"], ["Nova extensão para VS Code", "Escreva, execute e explore a linguagem sem sair do editor.", "Ferramentas"], ["Novos recursos da linguagem", "Imports nativos e uma API mais expressiva para aplicações.", "Linguagem"]];
export function PageHeading({ eyebrow, title, text }) { return <header className="page-heading"><p>{eyebrow}</p><h1>{title}</h1>{text && <span>{text}</span>}</header>; }
function SectionTitle({ eyebrow, title, text }) { return <header className="section-heading"><p>{eyebrow}</p><h2>{title}</h2>{text && <span>{text}</span>}</header>; }
export function DocumentationSection() { return <section className="section"><SectionTitle eyebrow="DOCUMENTAÇÃO" title="Tudo para começar bem." text="Encontre referências, guias e exemplos sem perder o foco." /><div className="docs-panel"><div><span className="search">⌕ Pesquisar na documentação...</span><a href="#/docs">Primeiros passos <b>→</b></a><a href="#/docs">Tipos e variáveis <b>→</b></a><a href="#/docs">Funções <b>→</b></a></div><pre><small>primeiros-passos.jls</small>{`\n\n// Seu primeiro programa\nmostrar("Olá, Mundo!")\n\nva linguagem = "JLScript"\nmostrar(linguagem)`}</pre></div></section>; }
export function InstallSection() { return <section className="section install-section"><SectionTitle eyebrow="INSTALAÇÃO" title="Pronta para o seu sistema." /><div className="install-grid">{[["Windows", "jls install"], ["Linux", "curl -fsSL https://jlscript.dev/install.sh | bash"], ["macOS", "brew install jls"]].map(([os, cmd]) => <article className="install-card" key={os}><span>{os}</span><code>$ {cmd}</code><button aria-label={`Copiar comando de ${os}`}>⧉</button></article>)}</div></section>; }
export function DownloadSection() { return <section className="section download-section"><SectionTitle eyebrow="DOWNLOAD" title="Comece a criar hoje." text="Versão atual: v1.0.0" /><div className="download-grid">{downloads.map(([icon, title, detail, action]) => <article className="download-card" key={title}><span>{icon}</span><h3>{title}</h3><p>{detail}</p><a className={action === "Em breve" ? "disabled" : ""} href={action === "Baixar para Windows" ? "/downloads/JLScript-Setup-1.0.0.exe" : "#/suporte"}>{action} →</a></article>)}</div></section>; }
export function PlaygroundSection() { return <section className="playground-section"><div><p className="eyebrow">PLAYGROUND</p><h2>Teste ideias<br />diretamente no navegador.</h2><p>Em breve: um ambiente rápido para experimentar JLScript, compartilhar códigos e aprender na prática.</p><a className="btn" href="#/roadmap">Ver roadmap <b>→</b></a></div><div className="play-symbol">{`{ }`}</div></section>; }
export function LibrarySection() { return <section className="section library-section"><SectionTitle eyebrow="BIBLIOTECA" title="Módulos para expandir suas ideias." text="A biblioteca padrão é organizada por módulos oficiais, simples de encontrar e importar." /><div className="library-box"><pre>{`importe #math\nimporte #http\nimporte #json\nimporte #panda os #pd`}</pre><a className="btn-outline" href="#/docs">Explorar documentação →</a></div></section>; }
export function RoadmapSection() { return <section className="section roadmap-section"><SectionTitle eyebrow="ROADMAP" title="Uma linguagem em movimento." /><div className="roadmap-list">{[["feito", "Interpretador"], ["feito", "VS Code Extension"], ["agora", "Compilador"], ["agora", "Package Manager"], ["depois", "Playground Online"], ["depois", "Gerenciador de Dependências"], ["depois", "IDE Oficial"], ["depois", "Documentação Completa"]].map(([status, label]) => <div key={label}><span className={status}>{status === "feito" ? "✓" : status === "agora" ? "◌" : "○"}</span>{label}</div>)}</div></section>; }
export function BlogSection() { return <section className="section blog-section"><SectionTitle eyebrow="BLOG" title="O que está acontecendo." /><div className="blog-grid">{updates.map(([title, text, tag]) => <article className="blog-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p><a href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">Ler no GitHub →</a></article>)}</div></section>; }
export function CommunitySection() { return <section className="community-section"><p className="eyebrow">COMUNIDADE</p><h2>Vamos construir a JLScript juntos.</h2><p>A linguagem cresce quando ideias, código e pessoas se encontram.</p><div><a className="btn" href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">GitHub ↗</a><a className="btn-outline" href="#/docs">Documentação</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues" target="_blank" rel="noreferrer">Reportar Bug</a></div></section>; }
