import { assetUrl, downloads, VERSION } from "../data/downloads";

export function PageHeading({ eyebrow, title, text }) { return <header className="page-heading"><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></header>; }
export function SectionTitle({ eyebrow, title, text }) { return <header className="section-heading"><p>{eyebrow}</p><h2>{title}</h2>{text && <span>{text}</span>}</header>; }

export function InstallSection() { return <section className="section install-section"><SectionTitle eyebrow="INSTALACAO" title="Pronta para seu sistema." /><div className="install-grid">{[["Windows", "Baixe o instalador recomendado"], ["Linux e macOS", "curl -fsSL https://jlscript.dev/install.sh | bash"], ["Termux", "curl -fsSL https://jlscript.dev/install-termux.sh | bash"]].map(([os, cmd]) => <article className="install-card" key={os}><span>{os}</span><code>$ {cmd}</code></article>)}</div></section>; }
export function DownloadSection() { return <section className="section download-section"><SectionTitle eyebrow="DOWNLOAD" title="Escolha sua plataforma." text={`Versao atual: v${VERSION} · pacotes distribuidos pelas Releases oficiais.`} /><div className="download-grid">{downloads.map((item) => <article className="download-card" key={item.id}><span>{item.icon}</span><h3>{item.name}</h3><p>{item.detail}</p><a href={assetUrl(item.asset)}>Baixar →</a></article>)}</div></section>; }

const updates = [["Lançamento da versão 2.1", "CLI, interpretador, compilação inicial e JLAI disponíveis.", "RELEASE"], ["Extensão para VS Code", "Destaque de sintaxe, snippets e execução rápida.", "FERRAMENTAS"], ["Ecossistema em evolução", "Bibliotecas, APIs e documentação oficial em expansão.", "COMUNIDADE"]];
export function BlogSection() { return <section className="section blog-section"><SectionTitle eyebrow="BLOG" title="O que está acontecendo." /><div className="blog-grid">{updates.map(([title, text, tag]) => <article className="blog-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p><a href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">Ler no GitHub →</a></article>)}</div></section>; }
export function CommunitySection() { return <section className="community-section"><p className="eyebrow">COMUNIDADE</p><h2>Vamos construir a JLScript juntos.</h2><p>A linguagem cresce quando ideias, código e pessoas se encontram.</p><div><a className="btn" href="https://github.com/eohlczinn/JLScript" target="_blank" rel="noreferrer">GitHub ↗</a><a className="btn-outline" href="#/docs">Documentação</a><a className="btn-outline" href="https://github.com/eohlczinn/JLScript/issues" target="_blank" rel="noreferrer">Reportar Bug</a></div></section>; }
